import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useLocation } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Award,
  ArrowLeft,
  Loader2,
  Mail,
  CheckCircle2,
  ExternalLink,
  Trophy,
  HelpCircle,
  MessageCircle
} from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useHelpChat } from "@/contexts/HelpChatContext";
import CertificateCheckout from "@/components/CertificateCheckout";

interface ClaimCertificateProps {
  courseId: string;
  onNavigate: (page: string) => void;
}

interface Course {
  id: string;
  title: string;
  description?: string;
  gradeTier?: string;
  certificationType?: string; // Drizzle returns camelCase
}

interface CertificateData {
  id: string;
  verificationCode: string;
  studentName: string;
  courseTitle: string;
  completionDate: string;
  finalScore?: number;
  certificateType?: string;
  certificateUrl?: string;
  previewImageUrl?: string;
  certifierId?: string;
  certifierPublicId?: string;
}

export default function ClaimCertificate({ courseId, onNavigate }: ClaimCertificateProps) {
  const queryClient = useQueryClient();
  const [, navigate] = useLocation();
  const { setIsChatOpen } = useHelpChat();
  const [showCheckout, setShowCheckout] = useState(false);

  // Get course details
  const { data: course, isLoading: courseLoading } = useQuery<Course>({
    queryKey: [`/api/course-creator/courses/${courseId}`],
    queryFn: async () => {
      const data = await apiRequest(`/api/course-creator/courses/${courseId}`);
      return data.course;
    }
  });

  // Get or check for existing certificate
  const { data: certificate, isLoading: certLoading } = useQuery<CertificateData | null>({
    queryKey: [`/api/certificates/course/${courseId}`],
    queryFn: async () => {
      try {
        const response = await apiRequest(`/api/certificates/course/${courseId}`);
        // Unwrap certificate from response
        const cert = response?.certificate || response;
        if (cert && cert.id) {
          return cert;
        }
      } catch (error) {
        // Certificate doesn't exist yet
      }
      return null;
    }
  });

  // Check if user has already purchased the certificate
  const { data: purchaseStatus, isLoading: purchaseLoading } = useQuery<{
    purchased: boolean;
    certificateType?: string;
    certificateId?: string;
  }>({
    queryKey: [`/api/certificates/purchase-status/${courseId}`],
    queryFn: async () => {
      try {
        const response = await apiRequest(`/api/certificates/purchase-status/${courseId}`);
        return response;
      } catch (error) {
        return { purchased: false };
      }
    }
  });

  // Generate certificate mutation
  const generateCertificateMutation = useMutation({
    mutationFn: async () => {
      // Check if certificate already exists before making the request
      if (certificate) {
        throw new Error('Certificate already exists for this course');
      }
      return await apiRequest('/api/certificates/generate', {
        method: 'POST',
        body: JSON.stringify({ courseId })
      });
    },
    onSuccess: (response) => {
      // Unwrap certificate from response
      const cert = response?.certificate || response;
      if (cert && cert.id) {
        queryClient.setQueryData([`/api/certificates/course/${courseId}`], cert);
      }
    },
    onError: (error: any) => {
      // Silent error handling - AJAX only
    }
  });

  // Resend certificate mutation (reuses the /generate endpoint)
  const resendCertificateMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest('/api/certificates/generate', {
        method: 'POST',
        body: JSON.stringify({ courseId })
      });
    },
    onSuccess: () => {
      // Silent success - AJAX only
    },
    onError: (error: any) => {
      // Silent error handling - AJAX only
    }
  });

  const handleClaimCertificate = () => {
    if (!certificate) {
      // Show checkout instead of generating immediately
      setShowCheckout(true);
    }
  };

  const handlePaymentSuccess = () => {
    // After payment, refetch certificate (it will be generated by backend)
    queryClient.invalidateQueries({ queryKey: [`/api/certificates/course/${courseId}`] });
    setShowCheckout(false);
  };

  const handleCancelCheckout = () => {
    setShowCheckout(false);
  };

  const certificateType = course?.certificationType === 'diploma' ? 'Diploma' : 'Certificate';

  if (courseLoading || certLoading || purchaseLoading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-[#ff5833] text-white sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => onNavigate(`course-player-${courseId}`)}
              data-testid="button-back-to-course"
              className="text-white hover:bg-white/10 p-2 rounded-lg transition-colors"
            >
              <ArrowLeft className="h-6 w-6" />
            </button>
            <div>
              <h1 className="text-xl md:text-2xl font-bold">Claim Your {certificateType}</h1>
              <p className="text-sm text-white/80">{course?.title}</p>
            </div>
          </div>
        </div>
      </div>
      {/* Main Content */}
      <div className="container mx-auto px-2 sm:px-4 py-4 sm:py-8 max-w-6xl">
        {certificate ? (
          <div className="max-w-4xl mx-auto">
            {/* Certificate Already Generated - Success View */}
            <div className="bg-gradient-to-r from-[#ff5834] to-[#ff7854] rounded-t-2xl p-4 sm:p-8 text-white shadow-xl">
              <div className="flex items-center gap-3 sm:gap-4">
                <div className="bg-white rounded-full p-2 sm:p-4 flex-shrink-0">
                  <CheckCircle2 className="h-10 w-10 sm:h-16 sm:w-16 text-[#ff5834]" />
                </div>
                <div>
                  <h2 className="text-xl sm:text-3xl md:text-4xl font-bold">Congratulations!</h2>
                  <p className="text-white/90 mt-1 sm:mt-2 text-sm sm:text-lg">Your {certificateType} Has Been Generated</p>
                </div>
              </div>
            </div>

            {/* Blue Email Notification Box */}
            <div className="bg-blue-50 dark:bg-blue-950 rounded-b-2xl p-4 sm:p-8">
              <div className="flex items-start gap-3 sm:gap-6">
                <div className="bg-blue-500 rounded-full p-2 sm:p-4 flex-shrink-0">
                  <Mail className="h-8 w-8 sm:h-12 sm:w-12 text-white" />
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="text-lg sm:text-2xl md:text-3xl font-bold text-blue-900 dark:text-blue-100 mb-2 sm:mb-3">
                    Certificate Sent to Your Email!
                  </h3>
                  <p className="text-sm sm:text-lg text-blue-700 dark:text-blue-200 mb-3 sm:mb-4">
                    We've sent your {certificateType.toLowerCase()} to your registered email address. 
                    Check your inbox for the official certificate document.
                  </p>
                  <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-4">
                    <div className="flex items-center gap-2 sm:gap-3 text-xs sm:text-base text-blue-600 dark:text-blue-300 bg-white dark:bg-blue-900 rounded-lg px-3 sm:px-4 py-2 sm:py-3 w-full sm:w-auto">
                      <CheckCircle2 className="h-4 w-4 sm:h-5 sm:w-5 flex-shrink-0" />
                      <span className="font-semibold">Email delivered successfully</span>
                    </div>
                    <Button
                      onClick={() => resendCertificateMutation.mutate()}
                      disabled={resendCertificateMutation.isPending}
                      variant="outline"
                      size="sm"
                      className="bg-white dark:bg-blue-900 border-2 border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-800 w-full sm:w-auto text-xs sm:text-sm"
                      data-testid="button-resend-certificate"
                    >
                      {resendCertificateMutation.isPending ? (
                        <>
                          <Loader2 className="h-3 w-3 sm:h-4 sm:w-4 mr-2 animate-spin" />
                          Resending...
                        </>
                      ) : (
                        <>
                          <Mail className="h-3 w-3 sm:h-4 sm:w-4 mr-2" />
                          Resend Certificate
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            {/* Support Contact Information */}
            <div 
              className="mt-4 sm:mt-6 bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-900 border-2 border-gray-300 dark:border-gray-600 rounded-2xl p-4 sm:p-6 cursor-pointer hover:border-gray-400 dark:hover:border-gray-500 transition-colors"
              onClick={() => setIsChatOpen(true)}
              data-testid="section-help-support"
            >
              <div className="flex items-start gap-3 sm:gap-4">
                <div className="bg-gray-600 dark:bg-gray-500 rounded-full p-2 sm:p-3 flex-shrink-0">
                  <HelpCircle className="h-6 w-6 sm:h-8 sm:w-8 text-white" />
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="text-base sm:text-xl font-bold text-gray-900 dark:text-gray-100 mb-1 sm:mb-2">
                    Having Problems Getting Your Documents?
                  </h3>
                  <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 mb-2 sm:mb-3">
                    If you haven't received your certificate or are experiencing any issues, click here to open our help chat. Our support team is ready to assist you!
                  </p>
                  <div className="flex items-center gap-2 text-xs sm:text-sm text-gray-600 dark:text-gray-400">
                    <MessageCircle className="h-3 w-3 sm:h-4 sm:w-4 flex-shrink-0" />
                    <span className="font-semibold">Click anywhere on this box to start a chat with support</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ) : purchaseStatus?.purchased ? (
          <div className="max-w-4xl mx-auto">
            {/* Already Purchased View */}
            <div className="bg-[#ff5834] rounded-t-2xl p-4 sm:p-8 text-white shadow-xl">
              <div>
                <h2 className="text-xl sm:text-3xl md:text-4xl font-bold text-white">Certificate Already Claimed!</h2>
                <p className="text-white/90 mt-1 sm:mt-2 text-sm sm:text-lg">Your {certificateType} is Ready</p>
              </div>
            </div>

            {/* Email Notification Box */}
            <div className="bg-blue-50 dark:bg-blue-950 rounded-b-2xl p-4 sm:p-8 shadow-xl">
              <p className="text-sm sm:text-lg text-blue-700 dark:text-blue-200 mb-3 sm:mb-4">
                Good news! You've already purchased this {certificateType.toLowerCase()}. 
                We've sent it to your registered email address.
              </p>
              <div className="space-y-2 sm:space-y-3 mb-4 sm:mb-6">
                <div className="flex items-center gap-2 sm:gap-3 text-xs sm:text-base text-blue-600 dark:text-blue-300 bg-white dark:bg-blue-900 rounded-lg px-3 sm:px-4 py-2 sm:py-3">
                  <CheckCircle2 className="h-4 w-4 sm:h-5 sm:w-5 flex-shrink-0" />
                  <span className="font-semibold">Certificate delivered successfully</span>
                </div>
                <div className="flex items-center gap-2 sm:gap-3 text-xs sm:text-base text-blue-600 dark:text-blue-300 bg-white dark:bg-blue-900 rounded-lg px-3 sm:px-4 py-2 sm:py-3">
                  <Award className="h-4 w-4 sm:h-5 sm:w-5 flex-shrink-0" />
                  <span className="font-semibold break-words">{course?.title}</span>
                </div>
              </div>
            </div>

            {/* Help Section */}
            <div 
              className="mt-4 sm:mt-6 bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-900 border-2 border-gray-300 dark:border-gray-600 rounded-2xl p-4 sm:p-6 cursor-pointer hover:border-gray-400 dark:hover:border-gray-500 transition-colors"
              onClick={() => setIsChatOpen(true)}
              data-testid="section-help-support-already-purchased"
            >
              <div className="flex items-start gap-3 sm:gap-4">
                <div className="bg-gray-600 dark:bg-gray-500 rounded-full p-2 sm:p-3 flex-shrink-0">
                  <HelpCircle className="h-6 w-6 sm:h-8 sm:w-8 text-white" />
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="text-base sm:text-xl font-bold text-gray-900 dark:text-gray-100 mb-1 sm:mb-2">
                    Didn't Receive Your Certificate?
                  </h3>
                  <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 mb-2 sm:mb-3">
                    Check your spam folder or contact our support team. We're here to help ensure you get your certificate!
                  </p>
                  <div className="space-y-1 sm:space-y-2">
                    <div className="flex items-center gap-2 text-xs sm:text-sm text-gray-600 dark:text-gray-400">
                      <MessageCircle className="h-3 w-3 sm:h-4 sm:w-4 flex-shrink-0" />
                      <span className="font-semibold">Click anywhere on this box to start a live chat with support</span>
                    </div>
                    <div className="flex items-center gap-2 text-xs sm:text-sm text-gray-600 dark:text-gray-400">
                      <Mail className="h-3 w-3 sm:h-4 sm:w-4 flex-shrink-0" />
                      <span>Email: support@edufiliova.com</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ) : showCheckout ? (
          <CertificateCheckout
            courseId={courseId}
            courseTitle={course?.title || ''}
            certificateType={certificateType}
            onSuccess={handlePaymentSuccess}
            onCancel={handleCancelCheckout}
          />
        ) : (
          <Card className="text-center p-12 shadow-none">
            <CardContent>
              <Trophy className="h-24 w-24 mx-auto mb-6 text-yellow-500" />
              <h2 className="text-3xl font-bold mb-4">Congratulations!</h2>
              <p className="text-lg text-muted-foreground mb-8">
                You've successfully completed <strong>{course?.title}</strong> and earned your {certificateType.toLowerCase()}!
              </p>
              <Button
                onClick={handleClaimCertificate}
                disabled={generateCertificateMutation.isPending}
                size="lg"
                className="bg-[#ff5833] hover:bg-[#e64a2a] text-white text-lg px-8 py-6"
                data-testid="button-generate-certificate"
              >
                {generateCertificateMutation.isPending ? "Generating..." : `Claim ${certificateType}`}
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
