export const WORLD_COUNTRIES = [
  // Africa
  { code: 'DZ', name: 'Algeria', gradeSystemType: 'Primary-Middle-Secondary' },
  { code: 'AO', name: 'Angola', gradeSystemType: 'Ensino-Basico-Secundario' },
  { code: 'BJ', name: 'Benin', gradeSystemType: 'French-Colonial' },
  { code: 'BW', name: 'Botswana', gradeSystemType: 'Primary-Junior-Senior' },
  { code: 'BF', name: 'Burkina Faso', gradeSystemType: 'French-Colonial' },
  { code: 'BI', name: 'Burundi', gradeSystemType: 'French-Colonial' },
  { code: 'CV', name: 'Cape Verde', gradeSystemType: 'Portuguese-Colonial' },
  { code: 'CM', name: 'Cameroon', gradeSystemType: 'Bilingual-System' },
  { code: 'CF', name: 'Central African Republic', gradeSystemType: 'French-Colonial' },
  { code: 'TD', name: 'Chad', gradeSystemType: 'French-Colonial' },
  { code: 'KM', name: 'Comoros', gradeSystemType: 'French-Colonial' },
  { code: 'CD', name: 'Democratic Republic of Congo', gradeSystemType: 'French-Colonial' },
  { code: 'CG', name: 'Republic of Congo', gradeSystemType: 'French-Colonial' },
  { code: 'CI', name: 'Ivory Coast', gradeSystemType: 'French-Colonial' },
  { code: 'DJ', name: 'Djibouti', gradeSystemType: 'French-Colonial' },
  { code: 'EG', name: 'Egypt', gradeSystemType: 'Primary-Preparatory-Secondary' },
  { code: 'GQ', name: 'Equatorial Guinea', gradeSystemType: 'Spanish-Colonial' },
  { code: 'ER', name: 'Eritrea', gradeSystemType: 'Elementary-Middle-Secondary' },
  { code: 'SZ', name: 'Eswatini', gradeSystemType: 'Primary-Junior-Senior' },
  { code: 'ET', name: 'Ethiopia', gradeSystemType: 'Primary-Secondary' },
  { code: 'GA', name: 'Gabon', gradeSystemType: 'French-Colonial' },
  { code: 'GM', name: 'Gambia', gradeSystemType: 'British-Colonial' },
  { code: 'GH', name: 'Ghana', gradeSystemType: 'Primary-JHS-SHS' },
  { code: 'GN', name: 'Guinea', gradeSystemType: 'French-Colonial' },
  { code: 'GW', name: 'Guinea-Bissau', gradeSystemType: 'Portuguese-Colonial' },
  { code: 'KE', name: 'Kenya', gradeSystemType: 'CBC-System' },
  { code: 'LS', name: 'Lesotho', gradeSystemType: 'Primary-Secondary' },
  { code: 'LR', name: 'Liberia', gradeSystemType: 'American-Style' },
  { code: 'LY', name: 'Libya', gradeSystemType: 'Basic-Secondary' },
  { code: 'MG', name: 'Madagascar', gradeSystemType: 'French-Colonial' },
  { code: 'MW', name: 'Malawi', gradeSystemType: 'Primary-Secondary' },
  { code: 'ML', name: 'Mali', gradeSystemType: 'French-Colonial' },
  { code: 'MR', name: 'Mauritania', gradeSystemType: 'French-Colonial' },
  { code: 'MU', name: 'Mauritius', gradeSystemType: 'British-French' },
  { code: 'MA', name: 'Morocco', gradeSystemType: 'Primary-College-Lycee' },
  { code: 'MZ', name: 'Mozambique', gradeSystemType: 'Portuguese-Colonial' },
  { code: 'NA', name: 'Namibia', gradeSystemType: 'Primary-Secondary' },
  { code: 'NE', name: 'Niger', gradeSystemType: 'French-Colonial' },
  { code: 'NG', name: 'Nigeria', gradeSystemType: 'Primary-JSS-SSS' },
  { code: 'RW', name: 'Rwanda', gradeSystemType: 'Primary-Secondary' },
  { code: 'ST', name: 'Sao Tome and Principe', gradeSystemType: 'Portuguese-Colonial' },
  { code: 'SN', name: 'Senegal', gradeSystemType: 'French-Colonial' },
  { code: 'SC', name: 'Seychelles', gradeSystemType: 'British-French' },
  { code: 'SL', name: 'Sierra Leone', gradeSystemType: 'British-Colonial' },
  { code: 'SO', name: 'Somalia', gradeSystemType: 'Primary-Intermediate-Secondary' },
  { code: 'ZA', name: 'South Africa', gradeSystemType: 'GET-FET' },
  { code: 'SS', name: 'South Sudan', gradeSystemType: 'Primary-Secondary' },
  { code: 'SD', name: 'Sudan', gradeSystemType: 'Basic-Secondary' },
  { code: 'TZ', name: 'Tanzania', gradeSystemType: 'Primary-Secondary' },
  { code: 'TG', name: 'Togo', gradeSystemType: 'French-Colonial' },
  { code: 'TN', name: 'Tunisia', gradeSystemType: 'Primary-Preparatory-Secondary' },
  { code: 'UG', name: 'Uganda', gradeSystemType: 'Primary-Secondary' },
  { code: 'ZM', name: 'Zambia', gradeSystemType: 'Primary-Secondary' },
  { code: 'ZW', name: 'Zimbabwe', gradeSystemType: 'Primary-Form-ALevel' },

  // Asia
  { code: 'AF', name: 'Afghanistan', gradeSystemType: 'Primary-Secondary' },
  { code: 'AM', name: 'Armenia', gradeSystemType: 'Primary-Basic-Senior' },
  { code: 'AZ', name: 'Azerbaijan', gradeSystemType: 'Primary-Basic-Senior' },
  { code: 'BH', name: 'Bahrain', gradeSystemType: 'Primary-Intermediate-Secondary' },
  { code: 'BD', name: 'Bangladesh', gradeSystemType: 'Primary-Secondary-HSC' },
  { code: 'BT', name: 'Bhutan', gradeSystemType: 'Primary-Lower-Middle-Higher' },
  { code: 'BN', name: 'Brunei', gradeSystemType: 'Primary-Secondary' },
  { code: 'KH', name: 'Cambodia', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'CN', name: 'China', gradeSystemType: 'Primary-Junior-Senior' },
  { code: 'CY', name: 'Cyprus', gradeSystemType: 'Primary-Gymnasium-Lyceum' },
  { code: 'GE', name: 'Georgia', gradeSystemType: 'Primary-Basic-Secondary' },
  { code: 'IN', name: 'India', gradeSystemType: 'Primary-Upper-Secondary-Senior' },
  { code: 'ID', name: 'Indonesia', gradeSystemType: 'SD-SMP-SMA' },
  { code: 'IR', name: 'Iran', gradeSystemType: 'Primary-Guidance-High' },
  { code: 'IQ', name: 'Iraq', gradeSystemType: 'Primary-Intermediate-Preparatory' },
  { code: 'IL', name: 'Israel', gradeSystemType: 'Elementary-Middle-High' },
  { code: 'JP', name: 'Japan', gradeSystemType: 'Elementary-Junior-Senior' },
  { code: 'JO', name: 'Jordan', gradeSystemType: 'Primary-Basic-Secondary' },
  { code: 'KZ', name: 'Kazakhstan', gradeSystemType: 'Primary-Basic-General' },
  { code: 'KW', name: 'Kuwait', gradeSystemType: 'Primary-Intermediate-Secondary' },
  { code: 'KG', name: 'Kyrgyzstan', gradeSystemType: 'Primary-Basic-General' },
  { code: 'LA', name: 'Laos', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'LB', name: 'Lebanon', gradeSystemType: 'Elementary-Intermediate-Secondary' },
  { code: 'MY', name: 'Malaysia', gradeSystemType: 'Primary-Secondary' },
  { code: 'MV', name: 'Maldives', gradeSystemType: 'Primary-Secondary' },
  { code: 'MN', name: 'Mongolia', gradeSystemType: 'Primary-Basic-Complete' },
  { code: 'MM', name: 'Myanmar', gradeSystemType: 'Primary-Middle-High' },
  { code: 'NP', name: 'Nepal', gradeSystemType: 'Basic-Secondary-Higher' },
  { code: 'KP', name: 'North Korea', gradeSystemType: 'Primary-Secondary' },
  { code: 'OM', name: 'Oman', gradeSystemType: 'Basic-Post-Basic' },
  { code: 'PK', name: 'Pakistan', gradeSystemType: 'Primary-Middle-Secondary-Intermediate' },
  { code: 'PS', name: 'Palestine', gradeSystemType: 'Basic-Secondary' },
  { code: 'PH', name: 'Philippines', gradeSystemType: 'Elementary-Junior-Senior' },
  { code: 'QA', name: 'Qatar', gradeSystemType: 'Primary-Preparatory-Secondary' },
  { code: 'SA', name: 'Saudi Arabia', gradeSystemType: 'Primary-Intermediate-Secondary' },
  { code: 'SG', name: 'Singapore', gradeSystemType: 'Primary-Secondary' },
  { code: 'KR', name: 'South Korea', gradeSystemType: 'Elementary-Middle-High' },
  { code: 'LK', name: 'Sri Lanka', gradeSystemType: 'Primary-Junior-Senior' },
  { code: 'SY', name: 'Syria', gradeSystemType: 'Basic-Secondary' },
  { code: 'TW', name: 'Taiwan', gradeSystemType: 'Elementary-Junior-Senior' },
  { code: 'TJ', name: 'Tajikistan', gradeSystemType: 'Primary-Basic-General' },
  { code: 'TH', name: 'Thailand', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'TL', name: 'Timor-Leste', gradeSystemType: 'Basic-Pre-Secondary-Secondary' },
  { code: 'TR', name: 'Turkey', gradeSystemType: 'Primary-Secondary' },
  { code: 'TM', name: 'Turkmenistan', gradeSystemType: 'Primary-Basic-General' },
  { code: 'AE', name: 'United Arab Emirates', gradeSystemType: 'Primary-Preparatory-Secondary' },
  { code: 'UZ', name: 'Uzbekistan', gradeSystemType: 'Primary-Basic-General' },
  { code: 'VN', name: 'Vietnam', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'YE', name: 'Yemen', gradeSystemType: 'Basic-Secondary' },

  // Europe
  { code: 'AL', name: 'Albania', gradeSystemType: 'Basic-Secondary' },
  { code: 'AD', name: 'Andorra', gradeSystemType: 'Primary-Secondary' },
  { code: 'AT', name: 'Austria', gradeSystemType: 'Primary-Secondary-Gymnasium' },
  { code: 'BY', name: 'Belarus', gradeSystemType: 'Primary-Basic-General' },
  { code: 'BE', name: 'Belgium', gradeSystemType: 'Primary-Secondary' },
  { code: 'BA', name: 'Bosnia and Herzegovina', gradeSystemType: 'Primary-Secondary' },
  { code: 'BG', name: 'Bulgaria', gradeSystemType: 'Primary-Progymnasium-Gymnasium' },
  { code: 'HR', name: 'Croatia', gradeSystemType: 'Primary-Secondary' },
  { code: 'CZ', name: 'Czech Republic', gradeSystemType: 'Basic-Secondary' },
  { code: 'DK', name: 'Denmark', gradeSystemType: 'Folkeskole-Gymnasium' },
  { code: 'EE', name: 'Estonia', gradeSystemType: 'Basic-Upper-Secondary' },
  { code: 'FI', name: 'Finland', gradeSystemType: 'Basic-Upper-Secondary' },
  { code: 'FR', name: 'France', gradeSystemType: 'Elementary-College-Lycee' },
  { code: 'DE', name: 'Germany', gradeSystemType: 'Primary-Secondary' },
  { code: 'GR', name: 'Greece', gradeSystemType: 'Primary-Gymnasium-Lyceum' },
  { code: 'HU', name: 'Hungary', gradeSystemType: 'Primary-Secondary' },
  { code: 'IS', name: 'Iceland', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'IE', name: 'Ireland', gradeSystemType: 'Primary-Post-Primary' },
  { code: 'IT', name: 'Italy', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'XK', name: 'Kosovo', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'LV', name: 'Latvia', gradeSystemType: 'Primary-Basic-Secondary' },
  { code: 'LI', name: 'Liechtenstein', gradeSystemType: 'Primary-Secondary' },
  { code: 'LT', name: 'Lithuania', gradeSystemType: 'Primary-Basic-Secondary' },
  { code: 'LU', name: 'Luxembourg', gradeSystemType: 'Primary-Secondary' },
  { code: 'MT', name: 'Malta', gradeSystemType: 'Primary-Secondary' },
  { code: 'MD', name: 'Moldova', gradeSystemType: 'Primary-Gymnasium-Lyceum' },
  { code: 'MC', name: 'Monaco', gradeSystemType: 'Elementary-College-Lycee' },
  { code: 'ME', name: 'Montenegro', gradeSystemType: 'Primary-Secondary' },
  { code: 'NL', name: 'Netherlands', gradeSystemType: 'Primary-Secondary' },
  { code: 'MK', name: 'North Macedonia', gradeSystemType: 'Primary-Secondary' },
  { code: 'NO', name: 'Norway', gradeSystemType: 'Primary-Lower-Upper' },
  { code: 'PL', name: 'Poland', gradeSystemType: 'Primary-Gymnasium-Secondary' },
  { code: 'PT', name: 'Portugal', gradeSystemType: 'Basic-Secondary' },
  { code: 'RO', name: 'Romania', gradeSystemType: 'Primary-Gymnasium-Lyceum' },
  { code: 'RU', name: 'Russia', gradeSystemType: 'Primary-Basic-Secondary' },
  { code: 'SM', name: 'San Marino', gradeSystemType: 'Elementary-Middle-High' },
  { code: 'RS', name: 'Serbia', gradeSystemType: 'Primary-Secondary' },
  { code: 'SK', name: 'Slovakia', gradeSystemType: 'Basic-Secondary' },
  { code: 'SI', name: 'Slovenia', gradeSystemType: 'Basic-Secondary' },
  { code: 'ES', name: 'Spain', gradeSystemType: 'Primary-ESO-Bachillerato' },
  { code: 'SE', name: 'Sweden', gradeSystemType: 'Grundskola-Gymnasium' },
  { code: 'CH', name: 'Switzerland', gradeSystemType: 'Primary-Secondary' },
  { code: 'UA', name: 'Ukraine', gradeSystemType: 'Primary-Basic-Senior' },
  { code: 'GB', name: 'United Kingdom', gradeSystemType: 'Primary-Secondary-Sixth' },
  { code: 'VA', name: 'Vatican City', gradeSystemType: 'Primary-Secondary' },

  // North America
  { code: 'AG', name: 'Antigua and Barbuda', gradeSystemType: 'Primary-Secondary' },
  { code: 'BS', name: 'Bahamas', gradeSystemType: 'Primary-Secondary' },
  { code: 'BB', name: 'Barbados', gradeSystemType: 'Primary-Secondary' },
  { code: 'BZ', name: 'Belize', gradeSystemType: 'Primary-Secondary' },
  { code: 'CA', name: 'Canada', gradeSystemType: 'Elementary-Secondary' },
  { code: 'CR', name: 'Costa Rica', gradeSystemType: 'Primary-Secondary-Diversified' },
  { code: 'CU', name: 'Cuba', gradeSystemType: 'Primary-Basic-Pre-University' },
  { code: 'DM', name: 'Dominica', gradeSystemType: 'Primary-Secondary' },
  { code: 'DO', name: 'Dominican Republic', gradeSystemType: 'Primary-Secondary' },
  { code: 'SV', name: 'El Salvador', gradeSystemType: 'Basic-Secondary-Bachillerato' },
  { code: 'GD', name: 'Grenada', gradeSystemType: 'Primary-Secondary' },
  { code: 'GT', name: 'Guatemala', gradeSystemType: 'Primary-Secondary-Diversified' },
  { code: 'HT', name: 'Haiti', gradeSystemType: 'Primary-Secondary' },
  { code: 'HN', name: 'Honduras', gradeSystemType: 'Primary-Secondary' },
  { code: 'JM', name: 'Jamaica', gradeSystemType: 'Primary-Secondary' },
  { code: 'MX', name: 'Mexico', gradeSystemType: 'Primary-Secondary-Bachillerato' },
  { code: 'NI', name: 'Nicaragua', gradeSystemType: 'Primary-Secondary' },
  { code: 'PA', name: 'Panama', gradeSystemType: 'Primary-Pre-Media-Media' },
  { code: 'KN', name: 'Saint Kitts and Nevis', gradeSystemType: 'Primary-Secondary' },
  { code: 'LC', name: 'Saint Lucia', gradeSystemType: 'Primary-Secondary' },
  { code: 'VC', name: 'Saint Vincent and Grenadines', gradeSystemType: 'Primary-Secondary' },
  { code: 'TT', name: 'Trinidad and Tobago', gradeSystemType: 'Primary-Secondary' },
  { code: 'US', name: 'United States', gradeSystemType: 'Elementary-Middle-High' },

  // South America
  { code: 'AR', name: 'Argentina', gradeSystemType: 'Primary-Secondary-Polimodal' },
  { code: 'BO', name: 'Bolivia', gradeSystemType: 'Primary-Secondary' },
  { code: 'BR', name: 'Brazil', gradeSystemType: 'Fundamental-Medio' },
  { code: 'CL', name: 'Chile', gradeSystemType: 'Basic-Secondary' },
  { code: 'CO', name: 'Colombia', gradeSystemType: 'Basic-Secondary-Media' },
  { code: 'EC', name: 'Ecuador', gradeSystemType: 'Basic-Bachillerato' },
  { code: 'FK', name: 'Falkland Islands', gradeSystemType: 'Primary-Secondary' },
  { code: 'GF', name: 'French Guiana', gradeSystemType: 'Elementary-College-Lycee' },
  { code: 'GY', name: 'Guyana', gradeSystemType: 'Primary-Secondary' },
  { code: 'PY', name: 'Paraguay', gradeSystemType: 'Basic-Secondary-Media' },
  { code: 'PE', name: 'Peru', gradeSystemType: 'Primary-Secondary' },
  { code: 'SR', name: 'Suriname', gradeSystemType: 'Basic-Secondary-VWO' },
  { code: 'UY', name: 'Uruguay', gradeSystemType: 'Primary-Secondary-Bachillerato' },
  { code: 'VE', name: 'Venezuela', gradeSystemType: 'Basic-Diversified-Media' },

  // Oceania
  { code: 'AU', name: 'Australia', gradeSystemType: 'Primary-Secondary' },
  { code: 'FJ', name: 'Fiji', gradeSystemType: 'Primary-Secondary' },
  { code: 'KI', name: 'Kiribati', gradeSystemType: 'Primary-Secondary' },
  { code: 'MH', name: 'Marshall Islands', gradeSystemType: 'Elementary-Secondary' },
  { code: 'FM', name: 'Micronesia', gradeSystemType: 'Elementary-Secondary' },
  { code: 'NR', name: 'Nauru', gradeSystemType: 'Primary-Secondary' },
  { code: 'NZ', name: 'New Zealand', gradeSystemType: 'Primary-Intermediate-Secondary' },
  { code: 'PW', name: 'Palau', gradeSystemType: 'Elementary-Secondary' },
  { code: 'PG', name: 'Papua New Guinea', gradeSystemType: 'Elementary-Secondary' },
  { code: 'WS', name: 'Samoa', gradeSystemType: 'Primary-Secondary' },
  { code: 'SB', name: 'Solomon Islands', gradeSystemType: 'Primary-Secondary' },
  { code: 'TO', name: 'Tonga', gradeSystemType: 'Primary-Secondary' },
  { code: 'TV', name: 'Tuvalu', gradeSystemType: 'Primary-Secondary' },
  { code: 'VU', name: 'Vanuatu', gradeSystemType: 'Primary-Secondary' }
];

export const COUNTRY_GRADE_SYSTEMS = {
  // Grade level mappings for different systems
  'Primary-Middle-Secondary': {
    'Primary': [1, 2, 3, 4, 5, 6],
    'Middle': [7, 8, 9],
    'Secondary': [10, 11, 12]
  },
  'Elementary-Middle-High': {
    'Elementary': [1, 2, 3, 4, 5],
    'Middle': [6, 7, 8],
    'High': [9, 10, 11, 12]
  },
  'Primary-Secondary': {
    'Primary': [1, 2, 3, 4, 5, 6, 7],
    'Secondary': [8, 9, 10, 11, 12]
  },
  'Primary-JSS-SSS': { // Nigeria system
    'Primary': [1, 2, 3, 4, 5, 6],
    'JSS': [7, 8, 9],
    'SSS': [10, 11, 12]
  },
  'Primary-Form-ALevel': { // Zimbabwe system
    'Primary': [1, 2, 3, 4, 5, 6, 7],
    'Form': [1, 2, 3, 4],
    'A-Level': [5, 6]
  },
  'GET-FET': { // South Africa system - Grade R to Grade 12
    'Foundation': ['R'], // Reception year
    'GET': [1, 2, 3, 4, 5, 6, 7, 8, 9], // General Education and Training
    'FET': [10, 11, 12] // Further Education and Training
  },
  'Primary-JHS-SHS': { // Ghana system
    'Primary': [1, 2, 3, 4, 5, 6],
    'JHS': [1, 2, 3],
    'SHS': [1, 2, 3]
  },
  'K12': { // US system
    'K': [0],
    'Elementary': [1, 2, 3, 4, 5],
    'Middle': [6, 7, 8],
    'High': [9, 10, 11, 12]
  },
  'Primary-Secondary-Sixth': { // UK system
    'Primary': [1, 2, 3, 4, 5, 6],
    'Secondary': [7, 8, 9, 10, 11],
    'Sixth Form': [12, 13]
  },
  // Add more as needed
};

export const CORE_SUBJECTS_BY_REGION = {
  'Global': [
    'Mathematics', 'English Language', 'Science', 'Biology', 'Chemistry', 'Physics',
    'Geography', 'History', 'Computer Science', 'Literature', 'Art & Design',
    'Physical Education', 'Music'
  ],
  'Africa': [
    'Mathematics', 'English Language', 'Science', 'Biology', 'Chemistry', 'Physics',
    'Geography', 'History', 'ICT', 'Literature', 'Religious & Moral Education', 'Civics',
    'Agriculture', 'Business Studies', 'Economics', 'Art & Design', 'Local Languages'
  ],
  'Asia': [
    'Mathematics', 'Science', 'Language Arts', 'Social Studies', 'Physical Education',
    'Arts & Crafts', 'Music', 'Moral Education', 'Computer Studies', 'Economics'
  ],
  'Europe': [
    'Mathematics', 'Language Arts', 'Science', 'History', 'Geography', 'Physical Education',
    'Arts', 'Music', 'Technology', 'Foreign Languages', 'Philosophy'
  ],
  'Americas': [
    'Mathematics', 'Language Arts', 'Science', 'Social Studies', 'Physical Education',
    'Arts', 'Music', 'Health', 'Technology', 'Career Education'
  ]
};